// A dedicated CODEX_HOME for chat models driven through the gateway.
// It keeps the user's own Codex setup (apps, plugins, MCP servers, skills) out of these sessions, describes each chat
// model in a model catalog (so Codex offers freeform apply_patch and uses its own base instructions), and turns off
// features a chat model behind a gateway cannot use: Codex's own sub-agents and goals, images, web search.
import fs from 'node:fs';
import path from 'node:path';
import { codexModelInfo } from './gateway.mjs';

/**
 * @param {{ dir: string, models: Array<{ name: string, label?: string, contextWindow?: number }> }} o
 * @returns {string} the directory, to pass as CODEX_HOME
 */
export function prepareCodexHome({ dir, models }) {
  fs.mkdirSync(dir, { recursive: true });
  const catalog = path.join(dir, 'catalog.json');
  fs.writeFileSync(catalog, JSON.stringify({ models: models.map(codexModelInfo) }));
  fs.writeFileSync(path.join(dir, 'config.toml'), `# Generated by chat-agent for chat models behind the Responses gateway.
model_catalog_json = ${JSON.stringify(catalog.split(path.sep).join('/'))}
web_search = "disabled"

[features]
multi_agent = false
goals = false
view_image = false
default_mode_request_user_input = false
apps = false
plugins = false
memories = false
standalone_web_search = false

[skills]
include_instructions = false
`);
  return dir;
}
